services:
  - type: web
    name: triad-documents
    env: node
    buildCommand: npm run build
    startCommand: node dist/index.js
    rootDir: .
    plan: starter
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: PORT
        value: 5002
      - key: NODE_ENV
        value: production
      - fromGroup: triad-shared-secrets
    autoDeploy: false
    domains:
      - docs.paintbrain.app

envVarGroups:
  - name: triad-shared-secrets
    envVars:
      - key: GOOGLE_SERVICE_ACCOUNT
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
